### PR TITLE
Put image link in right place

### PR DESCRIPTION
**Pull request by hflynn**
I will get this working!

### CODE REVIEW

**Comment by hflynn** [comment]
Okay, if this doesn't work when I've merged it, I'll need to add the full URL, but I can't test with the validator until this is live so merging now

**Comment by hflynn** [comment]
Okay, I'm mystified now - I'm not getting an error on the validator but when I submit the approval request for the whitelisting, I get an 'Error: is not a valid card type' message :(

error

Any ideas @lunson ?

**Comment by hflynn** [comment]
Double-checked from a browser I'm logged in as openmicroscopy on and it's definitely not an auth issue

**Comment by hflynn** [comment]
I'll try the full URL and see if that works

**Comment by hflynn** [comment]
Argh! Just worked it out - the card text has to be "summary" literally, not a summary!

**Comment by lunson** [comment]
Try all four meta tags: title, image, description, card: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by lunson** [comment]
Never mind... I think you've got it figured out.

**Pull request merged**
