### PR TITLE
Fix twitter preview image

### PR DESCRIPTION
**Pull request by hflynn**
Reading https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary I realized that #51 didn't work because I omitted the required `twitter:title` property.

It also tells me the image will be cropped to a square for all platforms so I've added a logo without the text too.

### CODE REVIEW

**Comment by hflynn** [comment]
@lunson look okay to you?

**Comment by lunson** [comment]
@hflynn Looks good. Hopefully it works!

**Comment by hflynn** [comment]
Hmm, still not working but maybe I didn't give it enough time to filter through the gh-pages. I'll try posting a link tomorrow and see if it works then!

**Comment by hflynn** [comment]
Ah, I used https://cards-dev.twitter.com/validator to test and the issue is that you need your content whitelisted by twitter!! Trying that now

**Comment by hflynn** [comment]
Ah, still complaining about the image link

**Pull request merged**
