### PR TITLE
Add %seo%

### PR DESCRIPTION
**Pull request by joshmoore**
See: https://help.github.com/articles/search-engine-optimization-for-github-pages/

### CODE REVIEW

**Comment by joshmoore** [comment]
Another possibility is: https://help.github.com/articles/sitemaps-for-github-pages/

**Comment by hflynn** [comment]
You need to add it to the Gemfile too @joshmoore

**Comment by hflynn** [comment]
I've realised this is going to conflict as soon as I merge the PR for the jekyll upgrade, will sort it out after that finally goes through!

**Comment by joshmoore** [comment]
No rush at all, @hflynn. This can also be cancelled, but rather than just open an RFE I figured I'd open a PR :smile:

**Comment by hflynn** [comment]
Yep, no problem.

**Comment by hflynn** [comment]
Replaced by #36 - closing

**Pull request closed without merging**
