### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by jburel**
Replace travis by actions 
see https://github.com/jburel/blog/actions/runs/366880688
cc @sbesson

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Thanks @jburel. Trying to look at the other Jekyll based repositories (www.openmicroscopy.org, idr.openmicroscopy.org), I was trying to identify whether the build + htmlproofer sequence could be generalized.

It looks like we would need to handle a few variants:

- configuration files passed via `--config` in the build step
- source of the folder to be linkchecked
- options passed to `htmlproofer` (`-disable-external`, `--file_ignore`_)

I did not find any straightforward way to move this to configuration files. So I think it's fine to have this merged and open similar changes to the other repositories.

Only question is whether it's preferable to list the commands explicitly in the `run` step of the GH actions or wrap them in a `build.sh` script that can be invoked. /cc @joshmoore

**Comment by jburel** [comment]
I looked at other repo and could not really find a common ground.
Having a script could be fine if one want to run it locally for testing purpose

**Comment by joshmoore** [comment]
I haven't looked at / thought about this case in any depth, but trying to keep the steps of the actions as re-usable as possible (similar to omero-test-infra) makes sense to me. In this case, that could be a script, or a Python library, or perhaps even a docker-compose.

**Comment by sbesson** [comment]
Merging and we can keep gaining experience of typical Jekyll workflows and see if the need for a common template arises. Main thought is that it is possible that blog will eventually get integrated into www which would limit the number of such repos.

**Pull request merged**
