### PR TITLE
Add pagination for Jekyll upgrade

### PR DESCRIPTION
**Pull request by hflynn**
GH pages is upgrading to Jekyll 3.1.2 imminently (see https://trello.com/c/ZWYMLh93/429-jekyll-upgrades-effects-on-github) so this fix is needed to keep the blog displaying properly.

To test: upgrade your local version of Jekyll to 3.1.2 (`gem update jekyll`) and build the blog locally (`jekyll serve`) WITHOUT this branch - you should have the expandable sidebar but no posts visible unless you select one via the categories list and a build warning about needing jekyll-paginate. Then fetch this branch and build it and you should have no build warnings and the blog should look as normal.

### CODE REVIEW

**Comment by will-moore** [comment]
This works fine as described. The only additional step I needed was the install itself.
```
$ sudo gem install jekyll-paginate
```
With this it builds fine and looks good.

**Comment by hflynn** [comment]
I'm now wondering if this is backwards compatible! Hopefully so, I'll see if I can test using my local repo

**Comment by hflynn** [comment]
Or not. Maybe I'll just hold off until gh-pages upgrades unless someone has an older version of jekyll to test this on. I didn't think about backwards compatibility until help staging didn't build correctly with the upgrade changes.

**Comment by hflynn** [comment]
gh-pages is now using Jekyll 3.1.6 which builds the blog fine with and without this change so closing PR as unneeded.

**Comment by hflynn** [comment]
Hmmm, I'm now getting a build warning about not having this plugin so I guess we do need this PR after all.

**Pull request merged**
